#!/bin/bash

# Install RNAVIEW
# based on https://github.com/fjossinet/RNArtistCore/blob/fda9898e796d234290dceded7ca0cc67e08fea69/Dockerfile
wget -qO RNAVIEW.tar.gz "http://ndbserver.rutgers.edu/ndbmodule/services/download/RNAVIEW.tar.gz"
tar -xzvf RNAVIEW.tar.gz
cd RNAVIEW/
make && make clean

# Add RNAVIEW to the path
mkdir -p ~/.local/bin
cd ~/.local/bin
ln -s ~/RNAVIEW/bin/rnaview RNAVIEW



### OLD SOURCE STUFF BELOW FROM failed attempt to install chimera in JupyterDesktop Binder at https://github.com/fomightez/Jupyter-desktop_with_chimera
# Install Chimera
# based on https://www.cgl.ucsf.edu/chimera/data/downloads/1.14/linux_x86_64.html
#chmod +x chimera-1.14-linux_x86_64.bin


# Add Chimera to the path
#mkdir -p ~/.local/bin
# to create alias for bendIt ("~/.local/bin" is in the PATH)
#cd ~/.local/bin
#ln -s ~/CHIMERA/bin/chimera chimera

