#!/bin/bash

# Install RNAVIEW
# based on https://github.com/fjossinet/RNArtistCore/blob/fda9898e796d234290dceded7ca0cc67e08fea69/Dockerfile
wget -qO RNAVIEW.tar.gz "http://ndbserver.rutgers.edu/ndbmodule/services/download/RNAVIEW.tar.gz"
tar -xzvf RNAVIEW.tar.gz
cd RNAVIEW/
make && make clean
cd ~
rm RNAVIEW.tar.gz

# set environmental variables - this handles adding to path so works, see https://twitter.com/rnartist_app/status/1369181657727664128
export RNAVIEW="$HOME/RNAVIEW"
export PATH=$RNAVIEW/bin:$PATH
# same need to be set in the `start` configuration so that survive to launching of session later


# retrieve rnartistcore and build  Kotlin library to describe and plot RNA secondary structures
git clone https://github.com/fjossinet/RNArtistCore.git
cd RNArtistCore/
git pull
mvn clean package

# move the demo notebook in RNArtistCore up to root since binder set up to use that notebook `rnartistcore_demo.ipynb` upon launch
mv rnartistcore_demo.ipynb ../.


### OLD SOURCE STUFF BELOW FROM failed attempt to install chimera in JupyterDesktop Binder at https://github.com/fomightez/Jupyter-desktop_with_chimera
# Install Chimera
# based on https://www.cgl.ucsf.edu/chimera/data/downloads/1.14/linux_x86_64.html
#chmod +x chimera-1.14-linux_x86_64.bin


# Add Chimera to the path
#mkdir -p ~/.local/bin
# to create alias for bendIt ("~/.local/bin" is in the PATH)
#cd ~/.local/bin
#ln -s ~/CHIMERA/bin/chimera chimera

